// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twbqumfpfnuqtdhdybrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3YnF1bWZwZm51cXRkaGR5YnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwNDAzMDUsImV4cCI6MjA1MjYxNjMwNX0.3wNwP8qGvlyi0Hqihvda0NmXHEwcZCYgUMQLapQFJo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);